{{- if and .Values.cilium.httproute.enabled .Values.opencloud.storage.s3.internal.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-minio-httproute
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  parentRefs:
    - name: {{ .Values.cilium.httproute.gateway.name }}
      namespace: {{ .Values.cilium.httproute.gateway.namespace | default .Values.namespace }}
      sectionName: minio-https
  hostnames:
    - {{ include "opencloud.minio.domain" . | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "opencloud.minio.fullname" . }}
          port: 9001
{{- end }}
