{{- if .Values.cilium.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "opencloud.fullname" . }}-reference-grant
  namespace: {{ .Values.cilium.httproute.gateway.namespace | default "kube-system" }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ include "opencloud.namespace" . }}
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.cilium.httproute.gateway.name }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "opencloud.fullname" . }}-cert-reference-grant
  namespace: {{ include "opencloud.namespace" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Values.cilium.httproute.gateway.namespace | default "kube-system" }}
  to:
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-opencloud-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-opencloud-minio-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-keycloak-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-collabora-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-collaboration-tls
    - group: ""
      kind: Secret
      name: {{ include "opencloud.fullname" . }}-wopi-tls
{{- end }}
