{{- if false }}
# Note: Using HTTPRoute instead of TLSRoute to support header modifications
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-wopi-tlsroute
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: wopiserver
spec:
  parentRefs:
    - name: {{ .Values.cilium.httproute.gateway.name }}
      namespace: {{ .Values.cilium.httproute.gateway.namespace | default .Values.namespace }}
      sectionName: wopi-https
  hostnames:
    - {{ .Values.global.domain.wopi | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: {{ .Values.global.domain.wopi | quote }}
      backendRefs:
        - name: {{ include "opencloud.fullname" . }}-wopiserver
          port: 8880
{{- end }}
